NordSecurity/rust_build_utils

.github/workflows/tests.yml, rust_build_utils/rust_utils.py
This will allow to run (build) nat-lab on macos host directly without needing to run nat-lab inside of the linux vm
=> Rust target for linux arm64

.github/workflows/docker.yml, .github/workflows/tests.yml, builders/package-aar-jdk-17/Dockerfile, rust_build_utils/android_build_utils.py, rust_build_utils/rust_utils.py, rust_sample/templates/__build.gradle, rust_sample/templates/__init.gradle, rust_sample/templates/__settings.gradle
This change adds 3 optional flags that can be used to customize `settings.gradle`, `build.gradle` and newly added `init.gradle`. This is because libtelio will need to customize those files to support `rustls-platform-verifier` which requires custom setup on android. Since that custom setup requires also newer gradle, a new docker aar image version is added which bumps gradle to `7.6.3` (which cause other things to be updated, like jdk version, and sdk tools - `ANDROID_COMPILE_SDK` still remains set to 29).
Tested with unmodified libtelio, where it worked correctly.
=> Add support for custom gradle files in aar generation and additional gradle 7.6 based docker image

builders/build-windows-rust/Dockerfile
Updates Go to latest stable version (1.21.6 at this time), which is required for libtelio to build latest wireguard-go. Additionally the `build-windows-rust` docker image is made smaller by removing temporary files after sccache compilation.
=> Update Go to 1.21.6 in build-windows-rust docker image

CHANGELOG.md, rust_build_utils/rust_utils_config.py
Until now rust flags for apple devices were being set on the GLOBAL_CONFIG dictionary. This disallow the developer to customize them as the flags on the script override the value set on the manifest file.
This commit removes this flags from the GLOBAL_CONFIG and the projects who were relying on it as default will have to set them on their manifest file instead.
=> Remove rustflags for apple builds

.github/workflows/test_build_docker.yml, rust_build_utils/rust_utils_config.py, rust_sample/ci/build_sample.py
With the upgrade to the latest rust version v1.77.2, the deployment versions have also to be updated. There was an issue with the static libraries using different linker versions on the sample project, so dynamic linking is now used.
=> Update iOS deployment target version

builders/package-aar-jdk-17/Dockerfile, builders/package-aar/Dockerfile
1. Add python3-pip to package-aar images.
2. Add `rm -rf /var/lib/apt/lists/*` after apt-get update to reduce image size
=> Add python3-pip to package-aar images

rust_build_utils/rust_utils.py
With libtelio's `rustc` and `Cargo.lock` update there's the need to also update rust for tvOS builds. This PR updates the nightly channel for these builds to `nightly-2024-01-25-aarch64-apple-darwin` with `rustc 1.77.0-nightly`.
=> build: Update nightly channel for tvos builds

.github/workflows/test_build_native.yml, .github/workflows/tests.yml, CHANGELOG.md, rust_build_utils/darwin_build_utils.py, rust_build_utils/rust_utils.py, rust_sample/ci/build_sample.py, rust_sample/src/sample.udl
1. Add functionality to build dylib darwin stub in order to build xcframework with dylibs.
2. Add functionality of generating uniffi bindings via rust_build_utils so that it can be easily done locally on developer's machine. 
Note: aar images were updated in: #11. pip module was installed
=> LLT-5033 dylib xcframework + uniffi bindings generation

builders/package-aar-jdk-17/Dockerfile
We started to use gradle 8.3.0 in libtelio. Without update package-aar build cannot succeed.
=> Bump gradle to 8.3.0

.github/workflows/tests.yml, rust_build_utils/rust_utils_config.py
`armv7` is used both for android and linux builds, however android translates to `armv7-eabi` while linux to `armv7-eabihf`.
This PR fixes this arch name difference to avoid future suprises.
=> Change linux armv7 arch name to armv7hf

.github/workflows/docker.yml, README.md, builders/package-aar-jdk-17/Dockerfile
1. Update README.md
Add information about debug docker images and do not allow pushing
release images from branches different then main
2. Update Gradle version in package-aar-jdk-17 image to 8.6
=> Update Gradle version in package-aar-jdk-17 image 

builders/build-linux-rust/Dockerfile
Remove `FROM` directive form the uniffi image and just copy binaries.
=> Fix uniffi binaries not appearing in linux image

.github/workflows/docker.yml, CHANGELOG.md, builders/build-linux-rust/Dockerfile
Until now only linux/amd64 images had been built. This meant that other platforms wouldn't work or had to use costly emulation (eg. on arm macos docker runs by default linux/arm64 but can emulate linux/amd64).
With this change build-linux-rust and build-linux-rust are made to work on linux/arm64 using `buildx` + `qemu`.
=> Build docker containers build-linux-rust and build-linux-rust for linux/arm64

.github/workflows/tests.yml, rust_build_utils/android_build_utils.py, rust_build_utils/darwin_build_utils.py, rust_build_utils/linux_build_utils.py, rust_build_utils/rust_utils.py, rust_build_utils/rust_utils_config.py
This PR introduces the following changes:
- Linux and Android release binaries are now fully stripped and their debug symbols compressed on a separate file.
- Android releases won't contain unstripped binaries anymore.
- Darwin release builds will be done with `split-debuginfo = "packed"` and `strip = true` cargo profile settings.
- Darwin releases will also include the respective dSYM bundles
=> LLT-5072: Investigate binary strip strategies

aar_templates/__build.gradle, rust_sample/templates/__build.gradle
In main there are 2 workflow job failing:
[test-android-artifacts](https://github.com/NordSecurity/rust_build_utils/actions/runs/11175996442/job/31068461779) and [test-android-artifacts-custom-files](https://github.com/NordSecurity/rust_build_utils/actions/runs/11175996442/job/31068461504)
with error:
> Could not find org.jfrog.buildinfo:build-info-extractor-gradle:4.18.2
It looks like this version is not available anymore in [https://jcenter.bintray.com/org/jfrog/buildinfo/build-info-extractor-gradle](https://jcenter.bintray.com/org/jfrog/buildinfo/build-info-extractor-gradle)
Hence updating references to the nearest version which is 4.23.4
=> Update build-info-extractor-gradle to 4.23.4

rust_build_utils/darwin_build_utils.py
Embedded paths in dylibs are absolute paths of
where they were built. This makes it so that on CI it embeds the full CI path of artefacts which is then traversed and the binary is not found when linking.
To fix that `install_name_tool` must be used.
The effects can be observed by using MacOS tool
called `otool`(part of XCode tools).
```
$ otool lib.dylib
...
Load command 3
cmd LC_ID_DYLIB
name /Users/[REDACTED]/target/lib.dylib
...
```
=> Fix paths for dylibs for Apple platforms

README.md, builders/build-linux-rust/Dockerfile, rust_build_utils/rust_utils_config.py
As devs we want to support qnap device and for that, it would be useful to have a docker image with the QDK framework already configured so that the final QPKG with the libtelio library can be built and ready to be installed onto the QNAP device.
=> Add qnap deps to linux builder docker image

builders/build-linux-rust/Dockerfile, rust_build_utils/rust_utils_config.py
Change qnap rust target triple from `x86_64-unknown-linux-gnu` to `x86_64-unknown-linux-musl`.
=> build: Change qnap triple to musl

.github/workflows/tests.yml, builders/build-android-rust/Dockerfile, builders/build-windows-rust/Dockerfile, rust_build_utils/rust_utils.py, rust_build_utils/rust_utils_config.py, rust_sample/ci/build_sample.py
Adding stubless `ios-sim` and `tvos-sim` build targets to darwin.
=> NUD-40 Build stubless library for darwin simulators

.github/workflows/test_build_docker.yml, .github/workflows/test_build_native.yml, .github/workflows/tests.yml, rust_build_utils/darwin_build_utils.py, rust_sample/ci/build_sample.py
This PR also contains the following fixes:
- Black linter has been updated by dependabot and it's now failing.
- actions/upload-artifact v3.x.x was deprecated and v4.x.x should be used.
- actions/download-artifact v3.x.x was deprecated and v4.x.x should be used.
see: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> Fix linter and deprecated actions

.github/workflows/docker.yml, rust_build_utils/rust_utils.py
Skip running post actions if all artifacts are unchanged.
Additionally, to fix segfaults under docker ([link](https://github.com/NordSecurity/rust_build_utils/actions/runs/13454646480/job/37596923484)) to changes are made:
- various docker related actions are updated to latest versions
- qemu image version is pinned to specific version that fixes the crash (this can be removed in future when https://github.com/docker/setup-qemu-action/issues/198 is fixed)
=> Run post actions lazily

builders/package-aar-jdk-17/Dockerfile
Bumping gradle version, to be able to use `com.android.tools.build:gradle:8.8.0` in gradle scripts, which mitigates [netty](https://nordsec.atlassian.net/browse/VCP-3655) vulnerability.
=> Bump gradle version to 8.10.2

builders/build-android-rust/Dockerfile, builders/build-linux-rust/Dockerfile, builders/build-windows-rust/Dockerfile, rust_build_utils/rust_utils_config.py, rust_sample/ci/build_sample.py
Due to LLT-6056: protobuf security vulnerability, we need to bump the rust tooling version to update the dependency. We would like update it to the latest stable release `v1.85.0`.
The rust version increase also necessitates the following changes:
- `sccache` removed due to build errors and reported incorrect outputs in `libtelio`.
- increased minimum macOS version from `v10.7` to `v10.12` due to [rustc compatibility](https://blog.rust-lang.org/2023/09/25/Increasing-Apple-Version-Requirements.html)
- removed `cargo search --limit` as it's not working as intended to populate the cache.
=> Bump rust version to 1.85.0

builders/build-linux-rust/Dockerfile, rust_build_utils/rust_utils_config.py
- Add aarch64-unknown-linux-musl support
=> LLT-6098: Use musl target for arm64 qnap

builders/build-android-rust/Dockerfile, builders/build-linux-rust/Dockerfile, builders/build-windows-rust/Dockerfile, builders/package-aar-jdk-17/Dockerfile, builders/package-aar/Dockerfile
This is required by the `tonic` crate which will be used to handle grpc for RFC-0091.
=> Add protoc compiler to images used for building

builders/build-linux-rust/Dockerfile, rust_build_utils/rust_utils_config.py
Reverts NordSecurity/rust_build_utils#48
In hindsight - it is not correct to augment linux builder image with all the possible targets since it's wasteful, it makes more sense to have a separate image(s) for OpenWRT targets.
For OpenWRT there are already images on docker hub for each target platform. For this I am using those images in CI/CD and reverting OpenWRT addition in here.
=> Revert "Openwrt support"

builders/build-linux-rust/Dockerfile, rust_build_utils/rust_utils_config.py
QNAP release is no longer planned due to meshnet sunset.
=> build: Drop QNAP support

rust_build_utils/rust_utils_config.py
Adding `control-flow-guard` to `windows` env, instead of per-arch basis.
=> Fix CFG windows

rust_build_utils/linux_build_utils.py, rust_build_utils/rust_utils_config.py
MIPS builds didn't have debug info. Now they will have it.
=> Add debug symbols for MIPS builds
